name: ASP.NET Core CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.301
    - name: Build with dotnet
      run: dotnet build --configuration Release
